services:
  influxdb2:
    env_file:
      - .env
    image: influxdb:2.7
    volumes:
      - influx_data:/var/lib/influxdb2

  influx-seed:
    env_file:
      - .env
    build:
      dockerfile: influx_seed.Dockerfile
    depends_on:
      - influxdb2

  db:  
    env_file:
      - .env
    image: mongo:7.0.5
    restart: always
    volumes:
      - mongo_data:/data/db
  
  mongo-seed:
    env_file:
      - .env
    build:
      dockerfile: mongo_seed.Dockerfile
    depends_on:
      - db

  backend:
    env_file:
      - .env
    build:
      dockerfile: backend.Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
      - influxdb2

  frontend:
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - "127.0.0.1:4433:80"
    depends_on:
      - backend
  
volumes:
  mongo_data:
  influx_data: