# compose.yaml
services:
  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: test_username
      DOCKER_INFLUXDB_INIT_PASSWORD: test_password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: test_token
      DOCKER_INFLUXDB_INIT_ORG: docs 
      DOCKER_INFLUXDB_INIT_BUCKET: test_bucket

  mongo:  
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  backend:
    build:
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - "81:80"

